### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by teonk** [Myrenic/HAWeightSensor2GarminConnect#1]
Hi,

Thanks for this great docker! Unfortunately I couldn't get it to run correctly.
I composed the image via Synology Container Manager according to the example you provided.

After starting the images in the logfiles I see: # | Error: Request failed with status code 404

The Yet Another Garmin Connect Client is running as I get reaction on http://internal-IP:555
This docker also doesn't show any errors, just normal feedback.

Is 404 a 'Page not found' ?
What could be the issue?
How can I enable debug logging?

**Comment by Myrenic** [comment]
Hey!

Thank you!

Could you post your entire docker-compose and the logs themselves? is there a chance you forgot the /upload part in: "YAGCC_API_URL=http://10.0.0.3:555/upload"?

the script should log any errors happening, if the error starts with "# | Error" it does not have a way to reach the YAGCC instance.

**Comment by Myrenic** [comment]
Hello,

I was able to reproduce your error, it seems like I need to update the docs since I have made some updates! If the HOME_ASSISTANT_IMPEDANCE_SENSOR variable is blank it will error out to 404.

If I find the time somewhere next week I'll add the error checking as well.

For now, you should be able to use this docker-compose setup to get it running:

```
  node-app:
    image: ghcr.io/myrenic/haweightsensor2garminconnect:main
    environment:
      - HOME_ASSISTANT_API_URL=https://home.example.com
      - HOME_ASSISTANT_ACCESS_TOKEN=ABCD12345
      - HOME_ASSISTANT_WEIGHT_SENSOR=input_number.weight #or any other. for example: sensor.weight
      - HOME_ASSISTANT_IMPEDANCE_SENSOR=input_number.impedance #or any other. for example: sensor.impedance
      - YAGCC_API_URL=http://10.0.0.3:555/upload
      - GARMIN_EMAIL=example@gmail.com
      - GARMIN_PASSWORD=password
      - USER_HEIGHT=180 #in CM
      - USER_SEX=male #or use female
      - USER_AGE=10
      - POLLING_INTERVAL=1800000 # In MS
    depends_on:
      - yagcc-api
```

Please let me know if it work! :)

**Comment by teonk** [comment]
The API url should be 10.0.0.3 or the local IP adres?
I tried both.
The /upload was in both tries there...

The log says:
`2024/03/04 20:00:39 | stdout | # \| Sleeping for 5 mins
2024/03/04 20:00:39 | stdout | # \| Closing loop
2024/03/04 20:00:39 | stderr | # \| Error: Request failed with status code 404
2024/03/04 20:00:39 | stdout | # \| Running loop
2024/03/04 20:00:38 | stdout | # \| Script started`

After recreating with the new docker compose, still the same error.

I left the HOME_ASSISTANT_IMPEDANCE_SENSOR empty. My scale/entity doesn't have one.
Could that be the cause?

**Comment by Myrenic** [comment]
Yep, that would most definitely be the issue. I updated the main loop to check if the impedance is provided, if not, it will only send the weight and it won't send any other metrics (as those rely on the impedance). Could you update your containers and give it a go and let me know if that works for you?

**Comment by teonk** [comment]
No, still a 404.

My docker compose is now:

```
version: "3.9"

services:
    node-app:
        container_name: HAWeightSensor2GarminConnect
        image: ghcr.io/myrenic/haweightsensor2garminconnect:main
        environment:
        - HOME_ASSISTANT_API_URL=http://192.168.0.26:8123
        - HOME_ASSISTANT_ACCESS_TOKEN=123456789
        - HOME_ASSISTANT_WEIGHT_SENSOR=sensor.teon_gewicht
        - HOME_ASSISTANT_IMPEDANCE_SENSOR=
        - YAGCC_API_URL=http://10.0.0.3:555/upload
        - GARMIN_EMAIL=MY@EMAIL.COM
        - GARMIN_PASSWORD=PASSWORD
        - USER_HEIGHT=192 #in CM
        - USER_SEX=male #or use female
        - USER_AGE=23
        - POLLING_INTERVAL=1800000 # In MS
        depends_on:
        - yagcc-api

    yagcc-api:
        container_name: YAGCC
        restart: unless-stopped
        image: lswiderski/yet-another-garmin-connect-client-api
        ports:
        - 555:80
```

Is the API-url correct or should it be my internal server (192.168.x.x.) or even docker adress (172.18.x.x.)?

**Comment by Myrenic** [comment]
You are really close, did you try to make it work without the empty HOME_ASSISTANT_IMPEDANCE_SENSOR variable?

**Comment by teonk** [comment]
Yes. In the compose above it was empty.

Is the API adress correct?

**Comment by Myrenic** [comment]
@teonk, i have added a lot more debugging to help you troubleshoot, could you please update our docker image?

**Comment by teonk** [comment]
I've updated the image and tried with and without the HOME_ASSISTANT_IMPEDANCE_SENSOR variable.

Both cases a 404.

Is the API-url correct or should it be my internal server (192.168.x.x.) or even docker adress (172.18.x.x.)?

**Comment by Myrenic** [comment]
Hey Teonk,

        - YAGCC_API_URL=http://10.0.0.3:555/upload

This should be the system running the YAGCC container, in my case 10.0.0.3.

**Comment by teonk** [comment]
I changed the API url but still a 404.

I now created this:

```
version: "3.9"

services:
    node-app:
        container_name: HAWeightSensor2GarminConnect
        image: ghcr.io/myrenic/haweightsensor2garminconnect:main
        environment:
        - HOME_ASSISTANT_API_URL=http://192.168.0.xx:8123
        - HOME_ASSISTANT_ACCESS_TOKEN=xxx
        - HOME_ASSISTANT_WEIGHT_SENSOR=sensor.teon_gewicht
        - HOME_ASSISTANT_IMPEDANCE_SENSOR=
        - YAGCC_API_URL=http://192.168.0.xx:555/upload
        - GARMIN_EMAIL=xxx@xx.com
        - GARMIN_PASSWORD=xxx
        - USER_HEIGHT=192 #in CM
        - USER_SEX=male #or use female
        - USER_AGE=xx
        - POLLING_INTERVAL=180000 # In MS
        depends_on:
        - yagcc-api

    yagcc-api:
        container_name: YAGCC
        restart: unless-stopped
        image: lswiderski/yet-another-garmin-connect-client-api
        ports:
        - 555:80
```

Could it be that Synology Container Manager needs to link the 2 containers?
How can I turn on deeper debugging?
